# AI Detection System Configuration

# Name of your AI assistant
ai_name: "Jarvis"

# Phonetic aliases (for when ASR misrecognizes the name)
# Add variations that your speech model transcribes incorrectly
ai_aliases:
  - "john wis"
  - "job is"
  - "john miss"

# Path to conversation log file (JSONL format)
log_file: "/home/paul/Work/jarvis/conversation.json"

# Model settings
model:
  # Use ML model for ambiguous cases (default: false, uses rule-based only)
  # Rule-based detection is much faster and works well for most cases
  use_model: false

  # Hugging Face model name for zero-shot classification (only if use_model: true)
  # Fast options:
  #   - typeform/distilbert-base-uncased-mnli (recommended - fast & accurate)
  #   - MoritzLaurer/multilingual-MiniLMv2-L6-mnli-xnli (smaller, faster)
  model_name: "typeform/distilbert-base-uncased-mnli"

  # Device: -1 for CPU, 0 for GPU (CUDA), 1+ for multi-GPU
  device: -1

# Detection settings
detection:
  # Confidence threshold (0.0 to 1.0)
  # Higher = stricter detection, fewer false positives
  # For zero-shot classification, 0.5-0.7 is a good range
  threshold: 0.65

  # Enable verbose logging
  verbose: false

# Output settings
output:
  # Log detection results to this file
  detection_log: "/home/paul/Work/jarvis/ai-detector/detections.log"
